chore: change to remote workflows
MapColonies/ts-server-boilerplate pull request #295
Opened 2024-02-26 14:37 UTC by michalby24

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| New feature     | ✔                                                                    |
| Chore            | ✔                                                                    |

Further  information:
use reusable workflows

2024-02-26 15:32 UTC, AnguIar requested changes
Good job :100:

2024-02-26 15:32 UTC, AnguIar commented on .github/workflows/pull_request.yaml
> +    secrets: inherit
Add new line

2024-02-26 15:32 UTC, AnguIar commented on .github/workflows/release-on-tag-push.yaml
> +    secrets: inherit
Add new line

2024-02-27 17:19 UTC, shimoncohen requested changes

2024-02-27 17:19 UTC, shimoncohen commented on .github/workflows/build-and-push.yaml
> +  reusable_workflow_job:
I think the job name should still be meaningful.
Same goes for other files.

2024-02-29 12:51 UTC, AnguIar approved these changes

2024-02-29 12:56 UTC, merged