chore: move husky to dev dep
MapColonies/ts-server-boilerplate pull request #321
Opened 2024-11-12 14:23 UTC by AnguIar

2024-11-12 14:31 UTC, netanelC requested changes
Good Job!
Run prettier

2024-11-12 18:42 UTC, shimoncohen requested changes

2024-11-12 18:42 UTC, shimoncohen commented on Dockerfile
> -COPY ./package*.json ./
We don't want to copy all files, it is better to add what we need explicitly.

2024-11-13 11:08 UTC, shimoncohen approved these changes

2024-11-13 11:30 UTC, CptSchnitz approved these changes

2024-11-13 11:34 UTC, merged