feat: added prometheus metrics integration
MapColonies/ts-server-boilerplate pull request #325
Opened 2024-11-26 12:02 UTC by CptSchnitz

2024-11-28 20:56 UTC, netanelC requested changes
Good PR. You have ESlint warnings

2024-12-04 17:44 UTC, shimoncohen approved these changes

2024-12-04 17:45 UTC, shimoncohen commented
And failing tests.

2024-12-04 17:46 UTC, shimoncohen requested changes
Some tests are failing.

2024-12-24 21:05 UTC, netanelC approved these changes

2024-12-29 13:53 UTC, shimoncohen approved these changes

2024-12-29 14:11 UTC, merged